/**
 * Environment Setup Utility
 * Issue #96: npm install CLI support
 * Migrated from scripts/setup-env.sh
 */

import {
  existsSync,
  writeFileSync,
  chmodSync,
  copyFileSync,
} from 'fs';
import { join, normalize } from 'path';
import { randomBytes } from 'crypto';
import {
  EnvConfig,
  EnvSetupOptions,
  ValidationResult,
} from '../types';

/**
 * Default environment configuration values
 * SF-4: DRY - Centralized defaults
 */
export const ENV_DEFAULTS = {
  CM_PORT: 3000,
  CM_BIND: '127.0.0.1',
  CM_DB_PATH: './data/cm.db',
  CM_LOG_LEVEL: 'info',
  CM_LOG_FORMAT: 'text',
} as const;

/**
 * Sanitize input by removing control characters
 * SF-SEC-3: Input sanitization
 */
export function sanitizeInput(input: string): string {
  // Remove control characters (0x00-0x1F and 0x7F)
  return input.replace(/[\x00-\x1F\x7F]/g, '');
}

/**
 * Sanitize path input
 * SF-SEC-3: Path sanitization
 */
export function sanitizePath(input: string): string {
  const sanitized = sanitizeInput(input);
  return normalize(sanitized);
}

/**
 * Validate port number
 * SF-SEC-3: Port validation
 */
export function validatePort(input: string): number {
  const port = parseInt(input, 10);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('Port must be an integer between 1 and 65535');
  }
  return port;
}

/**
 * Escape value for .env file
 * SF-SEC-3: Safe .env value escaping
 */
export function escapeEnvValue(value: string): string {
  // Escape backslashes and double quotes
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

  // Quote if contains special characters
  if (/[\s"'$`!]/.test(value)) {
    return `"${escaped}"`;
  }

  return value;
}

/**
 * Environment setup utility
 */
export class EnvSetup {
  private envPath: string;

  constructor(envPath?: string) {
    this.envPath = envPath || join(process.cwd(), '.env');
  }

  /**
   * Create .env file
   * SF-SEC-1: Sets file permissions to 0600
   */
  async createEnvFile(
    config: EnvConfig,
    options: EnvSetupOptions = {}
  ): Promise<void> {
    if (existsSync(this.envPath) && !options.force) {
      throw new Error('.env file already exists. Use --force to overwrite.');
    }

    // Build .env content
    const lines: string[] = [
      '# CommandMate Environment Configuration',
      '# Generated by commandmate init',
      '',
      `CM_ROOT_DIR=${escapeEnvValue(config.CM_ROOT_DIR)}`,
      `CM_PORT=${config.CM_PORT}`,
      `CM_BIND=${config.CM_BIND}`,
      `CM_DB_PATH=${escapeEnvValue(config.CM_DB_PATH)}`,
      `CM_LOG_LEVEL=${config.CM_LOG_LEVEL}`,
      `CM_LOG_FORMAT=${config.CM_LOG_FORMAT}`,
    ];

    if (config.CM_AUTH_TOKEN) {
      lines.push(`CM_AUTH_TOKEN=${config.CM_AUTH_TOKEN}`);
    }

    lines.push('');

    const content = lines.join('\n');

    // Write with secure permissions
    writeFileSync(this.envPath, content, { mode: 0o600 });

    // Ensure permissions are set (for existing file updates)
    chmodSync(this.envPath, 0o600);
  }

  /**
   * Backup existing .env file
   */
  async backupExisting(): Promise<string | null> {
    if (!existsSync(this.envPath)) {
      return null;
    }

    const timestamp = Date.now();
    const backupPath = `${this.envPath}.backup.${timestamp}`;
    copyFileSync(this.envPath, backupPath);

    return backupPath;
  }

  /**
   * Generate secure authentication token
   */
  generateAuthToken(): string {
    return randomBytes(32).toString('hex');
  }

  /**
   * Validate configuration
   */
  validateConfig(config: EnvConfig): ValidationResult {
    const errors: string[] = [];

    // Validate port
    if (config.CM_PORT < 1 || config.CM_PORT > 65535) {
      errors.push('Invalid port: must be between 1 and 65535');
    }

    // Validate bind address
    const validBinds = ['127.0.0.1', '0.0.0.0', 'localhost'];
    if (!validBinds.includes(config.CM_BIND)) {
      errors.push(`Invalid bind address: must be one of ${validBinds.join(', ')}`);
    }

    // Require auth token for external access
    if (config.CM_BIND === '0.0.0.0' && !config.CM_AUTH_TOKEN) {
      errors.push('auth token is required when binding to 0.0.0.0');
    }

    // Validate log level
    const validLogLevels = ['debug', 'info', 'warn', 'error'];
    if (!validLogLevels.includes(config.CM_LOG_LEVEL)) {
      errors.push(`Invalid log level: must be one of ${validLogLevels.join(', ')}`);
    }

    // Validate log format
    const validLogFormats = ['text', 'json'];
    if (!validLogFormats.includes(config.CM_LOG_FORMAT)) {
      errors.push(`Invalid log format: must be one of ${validLogFormats.join(', ')}`);
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }
}
